=== DaymareOn/FSMP-Validator/hdtSMP64.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<!-- simple elements -->
	<xsd:element name="angularOnly" type="xsd:boolean"/>
	<xsd:element name="angularBounce" type="vector3"/>
	<xsd:element name="angularDamping" type="float"/>
	<xsd:element name="angularEquilibrium" type="vector3"/>
	<!-- angularLowerLimit: if undefined, it's set to (1,1,1) -->
	<xsd:element name="angularLowerLimit" type="vector3"/>
	<xsd:element name="angularStiffness" type="vector3"/>
	<!-- angularUpperLimit: if undefined, it's set to (-1,-1,-1) -->
	<xsd:element name="angularUpperLimit" type="vector3"/>
	<xsd:element name="biasFactor" type="float"/>
	<xsd:element name="can-collide-with-bone" type="xsd:string"/>
	<xsd:element name="can-collide-with-tag" type="xsd:string"/>
	<xsd:element name="centerOfMassTransform" type="transform"/>
	<xsd:element name="collision-filter" type="xsd:int"/>
	<xsd:element name="coneLimit" type="float"/>
	<xsd:element name="damping" type="float"/>
	<xsd:element name="disable-priority" type="xsd:int"/>
	<xsd:element name="disable-tag" type="xsd:string"/>
	<xsd:element name="equilibrium" type="float"/>
	<xsd:element name="frameInA" type="transform"/>
	<xsd:element name="frameInB" type="transform"/>
	<xsd:element name="frameInLerp" type="lerp"/>
	<xsd:element name="friction" type="float"/>
	<xsd:element name="gravity-factor" type="float"/>
	<xsd:element name="half-extend" type="vector3"/>
	<xsd:element name="height" type="float"/>
	<xsd:element name="inertia" type="vector3"/>
	<xsd:element name="limitSoftness" type="float"/>
	<xsd:element name="limitX" type="float"/>
	<xsd:element name="limitY" type="float"/>
	<xsd:element name="limitZ" type="float"/>
	<xsd:element name="linearBounce" type="vector3"/>
	<xsd:element name="linearDamping" type="float"/>
	<xsd:element name="linearEquilibrium" type="vector3"/>
	<xsd:element name="linearLowerLimit" type="vector3"/>
	<xsd:element name="linearStiffness" type="vector3"/>
	<xsd:element name="linearUpperLimit" type="vector3"/>
	<xsd:element name="margin" type="float"/>
	<xsd:element name="margin-multiplier" type="float"/>
	<xsd:element name="mass" type="float"/>
	<xsd:element name="maxDistanceFactor" type="float"/>
	<xsd:element name="minDistanceFactor" type="float"/>
	<xsd:element name="no-collide-with-bone" type="xsd:string"/>
	<xsd:element name="no-collide-with-tag" type="xsd:string"/>
	<xsd:element name="penetration" type="float"/>
	<xsd:element name="planeLimit" type="float"/>
	<xsd:element name="point" type="vector3"/>
	<xsd:element name="prenetration" type="float"/>
	<xsd:element name="radius" type="float"/>
	<xsd:element name="relaxationFactor" type="float"/>
	<xsd:element name="restitution" type="float"/>
	<xsd:element name="rollingFriction" type="float"/>
	<xsd:element name="stiffness" type="float"/>
	<xsd:element name="swingSpan1" type="float"/>
	<xsd:element name="swingSpan2" type="float"/>
	<xsd:element name="tag" type="xsd:string"/>
	<xsd:element name="transform" type="transform"/>
	<xsd:element name="twistLimit" type="float"/>
	<xsd:element name="twistSpan" type="float"/>
	<xsd:element name="useLinearReferenceFrameA" type="xsd:boolean"/>
	<xsd:element name="wind-effect" type="float"/>
	<!-- complex elements -->
	<xsd:element name="shared">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:enumeration value="public"/>
				<xsd:enumeration value="private"/>
				<xsd:enumeration value="internal"/>
				<xsd:enumeration value="external"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>
	<!-- A "weight-threshold" in a "per-vertex-shape" or "per-triangle-shape"
         contains a float value and a "bone" attribute. Each skinned bone with
         that name in the "per-XXX-shape" has its weight-threshold set to the
         float value. This weight-threshold is used 3 ways:
         - When preparing collisions, no collision effect (displacement) is
           considered if the weight of the bone is zero or lower than the
           weight-threshold.
         - When processing collisions, when a collision happen between 2
           shapes, if the weight of the shape at the vertex or triangle
           collision point is lower than the weight-threshold defined for the
           vertex or triangle collision point bone, then the collision effects
           aren't applied.
         - In the CUDA version, the bone weight provided to the CUDA processor
           is the bone weight-threshold. -->
	<xsd:element name="weight-threshold">
		<xsd:complexType>
			<xsd:simpleContent>
				<xsd:extension base="float">
					<xsd:attribute name="bone" type="xsd:string"/>
				</xsd:extension>
			</xsd:simpleContent>
		</xsd:complexType>
	</xsd:element>
	<!-- containers -->
	<xsd:element name="per-triangle-shape">
		<xsd:annotation>
			<xsd:documentation>coucou</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:choice maxOccurs="unbounded">
				<xsd:element ref="margin"/>
				<xsd:element ref="prenetration"/>
				<xsd:element ref="penetration"/>
				<xsd:element ref="tag"/>
				<xsd:element ref="shared"/>
				<xsd:element ref="no-collide-with-tag"/>
				<xsd:element ref="no-collide-with-bone"/>
				<xsd:element ref="can-collide-with-tag"/>
				<xsd:element ref="can-collide-with-bone"/>
				<xsd:element ref="weight-threshold"/>
				<xsd:element ref="disable-tag"/>
				<xsd:element ref="disable-priority"/>
				<xsd:element ref="wind-effect"/>
			</xsd:choice>
			<xsd:attribute name="name" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<!-- per-vertex-shape: there is no penetration tag inside per-vertex-shape. -->
	<xsd:element name="per-vertex-shape">
		<xsd:complexType>
			<xsd:choice maxOccurs="unbounded">
				<xsd:element ref="margin"/>
				<xsd:element ref="tag"/>
				<xsd:element ref="shared"/>
				<xsd:element ref="no-collide-with-tag"/>
				<xsd:element ref="can-collide-with-tag"/>
				<xsd:element ref="no-collide-with-bone"/>
				<xsd:element ref="can-collide-with-bone"/>
				<xsd:element ref="weight-threshold"/>
				<xsd:element ref="disable-tag"/>
				<xsd:element ref="disable-priority"/>
				<xsd:element ref="wind-effect"/>
			</xsd:choice>
			<xsd:attribute name="name" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="bone-default">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="mass"/>
				<xsd:element ref="inertia"/>
				<xsd:element ref="centerOfMassTransform"/>
				<xsd:element ref="linearDamping"/>
				<xsd:element ref="angularDamping"/>
				<xsd:element ref="gravity-factor"/>
				<xsd:element ref="friction"/>
				<xsd:element ref="rollingFriction"/>
				<xsd:element ref="restitution"/>
				<xsd:element ref="margin-multiplier"/>
				<xsd:element ref="shape"/>
				<xsd:element ref="collision-filter"/>
				<xsd:element ref="can-collide-with-bone"/>
				<xsd:element ref="no-collide-with-bone"/>
			</xsd:choice>
			<xsd:attribute name="name" type="xsd:string"/>
			<xsd:attribute name="extends" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="bone">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="mass"/>
				<xsd:element ref="inertia"/>
				<xsd:element ref="centerOfMassTransform"/>
				<xsd:element ref="linearDamping"/>
				<xsd:element ref="angularDamping"/>
				<xsd:element ref="gravity-factor"/>
				<xsd:element ref="friction"/>
				<xsd:element ref="rollingFriction"/>
				<xsd:element ref="restitution"/>
				<xsd:element ref="margin-multiplier"/>
				<xsd:element ref="shape"/>
				<xsd:element ref="collision-filter"/>
				<xsd:element ref="can-collide-with-bone"/>
				<xsd:element ref="no-collide-with-bone"/>
			</xsd:choice>
			<xsd:attribute name="name" type="xsd:string"/>
			<xsd:attribute name="extends" type="xsd:string"/>
			<xsd:attribute name="template" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="generic-constraint-default">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="angularBounce"/>
				<xsd:element ref="angularEquilibrium"/>
				<xsd:element ref="angularLowerLimit"/>
				<xsd:element ref="angularUpperLimit"/>
				<xsd:element ref="angularStiffness"/>
				<xsd:element ref="frameInA"/>
				<xsd:element ref="frameInB"/>
				<xsd:element ref="frameInLerp"/>
				<xsd:element ref="linearBounce"/>
				<xsd:element ref="linearEquilibrium"/>
				<xsd:element ref="linearLowerLimit"/>
				<xsd:element ref="linearUpperLimit"/>
				<xsd:element ref="linearStiffness"/>
				<xsd:element ref="useLinearReferenceFrameA"/>
				<!-- linear and angular damping are already declared as floats for bones -->
				<xsd:element name="angularDamping" type="vector3"/>
				<xsd:element name="linearDamping" type="vector3"/>
			</xsd:choice>
			<xsd:attribute name="name" type="xsd:string"/>
			<xsd:attribute name="extends" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="stiffspring-constraint-default">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="minDistanceFactor"/>
				<xsd:element ref="maxDistanceFactor"/>
				<xsd:element ref="stiffness"/>
				<xsd:element ref="damping"/>
				<xsd:element ref="equilibrium"/>
			</xsd:choice>
			<xsd:attribute name="name" type="xsd:string"/>
			<xsd:attribute name="extends" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="stiffspring-constraint">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="minDistanceFactor"/>
				<xsd:element ref="maxDistanceFactor"/>
				<xsd:element ref="stiffness"/>
				<xsd:element ref="damping"/>
				<xsd:element ref="equilibrium"/>
			</xsd:choice>
			<xsd:attribute name="bodyA" type="xsd:string"/>
			<xsd:attribute name="bodyB" type="xsd:string"/>
			<xsd:attribute name="template" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="conetwist-constraint-default">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="frameInA"/>
				<xsd:element ref="frameInB"/>
				<xsd:element ref="frameInLerp"/>
				<xsd:element ref="angularOnly"/>
				<xsd:element ref="swingSpan1"/>
				<xsd:element ref="swingSpan2"/>
				<xsd:element ref="twistSpan"/>
				<xsd:element ref="coneLimit"/>
				<xsd:element ref="planeLimit"/>
				<xsd:element ref="twistLimit"/>
				<xsd:element ref="limitX"/>
				<xsd:element ref="limitY"/>
				<xsd:element ref="limitZ"/>
				<xsd:element ref="limitSoftness"/>
				<xsd:element ref="biasFactor"/>
				<xsd:element ref="relaxationFactor"/>
			</xsd:choice>
			<xsd:attribute name="name" type="xsd:string"/>
			<xsd:attribute name="extends" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="conetwist-constraint">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="frameInA"/>
				<xsd:element ref="frameInB"/>
				<xsd:element ref="frameInLerp"/>
				<xsd:element ref="angularOnly"/>
				<xsd:element ref="swingSpan1"/>
				<xsd:element ref="swingSpan2"/>
				<xsd:element ref="twistSpan"/>
				<xsd:element ref="coneLimit"/>
				<xsd:element ref="planeLimit"/>
				<xsd:element ref="twistLimit"/>
				<xsd:element ref="limitX"/>
				<xsd:element ref="limitY"/>
				<xsd:element ref="limitZ"/>
				<xsd:element ref="limitSoftness"/>
				<xsd:element ref="biasFactor"/>
				<xsd:element ref="relaxationFactor"/>
			</xsd:choice>
			<xsd:attribute name="bodyA" type="xsd:string"/>
			<xsd:attribute name="bodyB" type="xsd:string"/>
			<xsd:attribute name="template" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="generic-constraint">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="angularBounce"/>
				<xsd:element ref="angularEquilibrium"/>
				<xsd:element ref="angularLowerLimit"/>
				<xsd:element ref="angularStiffness"/>
				<xsd:element ref="angularUpperLimit"/>
				<xsd:element ref="frameInA"/>
				<xsd:element ref="frameInB"/>
				<xsd:element ref="frameInLerp"/>
				<xsd:element ref="linearBounce"/>
				<xsd:element ref="linearEquilibrium"/>
				<xsd:element ref="linearLowerLimit"/>
				<xsd:element ref="linearStiffness"/>
				<xsd:element ref="linearUpperLimit"/>
				<xsd:element ref="useLinearReferenceFrameA"/>
				<!-- linear and angular damping are already declared as floats for bones -->
				<xsd:element name="linearDamping" type="vector3"/>
				<xsd:element name="angularDamping" type="vector3"/>
			</xsd:choice>
			<xsd:attribute name="bodyA" type="xsd:string"/>
			<xsd:attribute name="bodyB" type="xsd:string"/>
			<xsd:attribute name="template" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="constraint-group">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="generic-constraint"/>
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>
	<xsd:simpleType name="shapeType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="ref"/>
			<xsd:enumeration value="box"/>
			<xsd:enumeration value="sphere"/>
			<xsd:enumeration value="capsule"/>
			<xsd:enumeration value="hull"/>
			<xsd:enumeration value="cylinder"/>
			<xsd:enumeration value="compound"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:element name="shape">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<!-- for type box -->
				<xsd:element ref="half-extend"/>
				<!-- for types box, hull and cylinder -->
				<xsd:element ref="margin"/>
				<!-- for types sphere, capsule and cylinder -->
				<xsd:element ref="radius"/>
				<!-- for types capsule and cylinder -->
				<xsd:element ref="height"/>
				<!-- for type hull -->
				<xsd:element ref="point"/>
				<!-- for type compound -->
				<xsd:element ref="child"/>
			</xsd:choice>
			<xsd:attribute name="name" type="xsd:string"/>
			<xsd:attribute name="type" type="shapeType"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="child">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="transform"/>
				<xsd:element ref="shape"/>
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="system">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="per-triangle-shape"/>
				<xsd:element ref="per-vertex-shape"/>
				<xsd:element ref="bone-default"/>
				<xsd:element ref="bone"/>
				<xsd:element ref="shape"/>
				<xsd:element ref="generic-constraint-default"/>
				<xsd:element ref="stiffspring-constraint-default"/>
				<xsd:element ref="conetwist-constraint-default"/>
				<xsd:element ref="generic-constraint"/>
				<xsd:element ref="stiffspring-constraint"/>
				<xsd:element ref="conetwist-constraint"/>
				<xsd:element ref="constraint-group"/>
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>
	<!-- New types -->
	<xsd:complexType name="vector3">
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute name="x" type="float"/>
				<xsd:attribute name="y" type="float"/>
				<xsd:attribute name="z" type="float"/>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
	<xsd:complexType name="quaternion">
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute name="x" type="float"/>
				<xsd:attribute name="y" type="float"/>
				<xsd:attribute name="z" type="float"/>
				<xsd:attribute name="w" type="float"/>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
	<xsd:complexType name="axisAngle">
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute name="x" type="float"/>
				<xsd:attribute name="y" type="float"/>
				<xsd:attribute name="z" type="float"/>
				<xsd:attribute name="angle" type="float"/>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
	<xsd:complexType name="transform">
		<xsd:choice minOccurs="0" maxOccurs="unbounded">
			<xsd:element name="basis" type="quaternion"/>
			<xsd:element name="basis-axis-angle" type="axisAngle"/>
			<xsd:element name="origin" type="vector3"/>
		</xsd:choice>
	</xsd:complexType>
	<xsd:complexType name="lerp">
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute name="translationLerp" type="float"/>
				<xsd:attribute name="rotationLerp" type="float"/>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
	<xsd:simpleType name="float">
		<xsd:restriction base="xsd:float">
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== DaymareOn/FSMP-Validator/examples/creature-wolf-tail/SKSE/Plugins/hdtSkinnedMeshConfigs/FSMP_Example_WolfTail.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://raw.githubusercontent.com/DaymareOn/FSMP-Validator/refs/heads/main/skse/plugins/hdtSkinnedMeshConfigs/hdtSMP64.sch" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<!--
  FSMP creature-physics example: a physics-driven tail for canines (wolf / dog / fox).

  Bone-only system: it declares no mesh shape. SMP simulates the tail bones as rigid bodies and
  writes their transforms back to the skeleton every frame; the creature's own vanilla tail mesh is
  skinned to those bones, so it simply follows. That is why this needs no new or edited mesh.

  Bones (vanilla Bethesda canine skeleton names, preserved by XPMSSE):
    Canine_Pelvis    - kinematic anchor: declared before the <bone-default> below, so it uses the
                       built-in default template (mass 0 = kinematic) and stays glued to the body.
    Canine_Tail1/2/3 - dynamic: declared after the mass-bearing <bone-default>, so they swing.
-->
<system xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="FSMP-Validator" xsi:schemaLocation="FSMP-Validator https://raw.githubusercontent.com/DaymareOn/FSMP-Validator/main/skse/plugins/hdtSkinnedMeshConfigs/hdtSMP64.xsd">

    <!-- Kinematic anchor (mass 0 via the built-in default template). Must precede the <bone-default>. -->
    <bone name="Canine_Pelvis"/>

    <!-- From here on, bones are dynamic. -->
    <bone-default>
        <mass>1.5</mass>
        <inertia x="15" y="15" z="15"/>
        <centerOfMassTransform>
            <basis x="0" y="0" z="0" w="1"/>
            <origin x="0" y="0" z="0"/>
        </centerOfMassTransform>
        <linearDamping>0.6</linearDamping>
        <angularDamping>0.7</angularDamping>
        <friction>0.5</friction>
        <rollingFriction>0.5</rollingFriction>
        <restitution>0.2</restitution>
        <margin-multiplier>1</margin-multiplier>
        <gravity-factor>1.0</gravity-factor>
    </bone-default>
    <bone name="Canine_Tail1"/>
    <bone name="Canine_Tail2"/>
    <bone name="Canine_Tail3"/>

    <!-- One hinge template reused by every segment. Loose cone so the tail visibly droops and swings,
         but bounded so it cannot fold back on itself and destabilise the simulation. No springs:
         gravity and the creature's motion drive it. -->
    <generic-constraint-default>
        <frameInB>
            <basis x="0" y="0" z="0" w="1"/>
            <origin x="0" y="0" z="0"/>
        </frameInB>
        <useLinearReferenceFrameA>false</useLinearReferenceFrameA>
        <linearLowerLimit x="0" y="0" z="0"/>
        <linearUpperLimit x="0" y="0" z="0"/>
        <angularLowerLimit x="-0.6" y="-0.4" z="-0.6"/>
        <angularUpperLimit x="0.6" y="0.4" z="0.6"/>
        <linearStiffness x="0" y="0" z="0"/>
        <angularStiffness x="0" y="0" z="0"/>
        <linearDamping x="0" y="0" z="0"/>
        <angularDamping x="0" y="0" z="0"/>
        <linearEquilibrium x="0" y="0" z="0"/>
        <angularEquilibrium x="0" y="0" z="0"/>
    </generic-constraint-default>

    <constraint-group>
        <generic-constraint bodyA="Canine_Tail1" bodyB="Canine_Pelvis"/>
        <generic-constraint bodyA="Canine_Tail2" bodyB="Canine_Tail1"/>
        <generic-constraint bodyA="Canine_Tail3" bodyB="Canine_Tail2"/>
    </constraint-group>

</system>

=== DaymareOn/FSMP-Validator/examples/creature-horse-tail/SKSE/Plugins/hdtSkinnedMeshConfigs/FSMP_Example_HorseTail.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://raw.githubusercontent.com/DaymareOn/FSMP-Validator/refs/heads/main/skse/plugins/hdtSkinnedMeshConfigs/hdtSMP64.sch" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<!--
  FSMP creature-physics example: a physics-driven tail for horses.

  Bone-only system: it declares no mesh shape. SMP simulates the tail bones as rigid bodies and writes
  their transforms back to the skeleton every frame; the horse's own vanilla tail mesh is skinned to
  those bones, so it simply follows. That is why this needs no new or edited mesh.

  Bones (present in every horse skeleton — vanilla, XPMSSE, War Horse, Slim Horse):
    HorsePelvis        - kinematic anchor: declared before the <bone-default>, so it uses the built-in
                         default template (mass 0 = kinematic) and stays glued to the horse's body.
    HorseTail1..Tail4  - dynamic: declared after the mass-bearing <bone-default>, so they swing. These
                         are the vanilla tail bones the tail mesh is skinned to, so making them dynamic
                         moves the visible tail (physics replaces the scripted tail-swish animation).

  Only non-default values are written, so this file reports no "unnecessary tag" warnings in smp report.
-->
<system xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="FSMP-Validator" xsi:schemaLocation="FSMP-Validator https://raw.githubusercontent.com/DaymareOn/FSMP-Validator/main/skse/plugins/hdtSkinnedMeshConfigs/hdtSMP64.xsd">

    <!-- Kinematic anchor (mass 0 via the built-in default template). Must precede the <bone-default>. -->
    <bone name="HorsePelvis"/>

    <!-- From here on, bones are dynamic: a light segment with a little damping so the tail settles
         instead of jittering. -->
    <bone-default>
        <mass>1.5</mass>
        <inertia x="15" y="15" z="15"/>
        <linearDamping>0.6</linearDamping>
        <angularDamping>0.7</angularDamping>
        <rollingFriction>0.5</rollingFriction>
        <restitution>0.2</restitution>
    </bone-default>
    <bone name="HorseTail1"/>
    <bone name="HorseTail2"/>
    <bone name="HorseTail3"/>
    <bone name="HorseTail4"/>

    <!-- One hinge template reused by every segment. The linear axes are locked (lower = upper = 0) so
         segments only rotate, and the angular limits give a loose cone so the tail visibly droops and
         swings but cannot fold back on itself. No springs: gravity and the horse's motion drive it. -->
    <generic-constraint-default>
        <linearLowerLimit x="0" y="0" z="0"/>
        <linearUpperLimit x="0" y="0" z="0"/>
        <angularLowerLimit x="-0.6" y="-0.4" z="-0.6"/>
        <angularUpperLimit x="0.6" y="0.4" z="0.6"/>
    </generic-constraint-default>

    <constraint-group>
        <generic-constraint bodyA="HorseTail1" bodyB="HorsePelvis"/>
        <generic-constraint bodyA="HorseTail2" bodyB="HorseTail1"/>
        <generic-constraint bodyA="HorseTail3" bodyB="HorseTail2"/>
        <generic-constraint bodyA="HorseTail4" bodyB="HorseTail3"/>
    </constraint-group>

</system>

=== DaymareOn/FSMP-Validator/examples/crossed-cloak/SKSE/Plugins/hdtSkinnedMeshConfigs/cloak.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://raw.githubusercontent.com/DaymareOn/FSMP-Validator/da42538f0442583349b3774b8c0fd9a6551bf78a/skse/plugins/hdtSkinnedMeshConfigs/hdtSMP64.sch" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<system xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="FSMP-Validator" xsi:schemaLocation="FSMP-Validator https://raw.githubusercontent.com/DaymareOn/FSMP-Validator/da42538f0442583349b3774b8c0fd9a6551bf78a/skse/plugins/hdtSkinnedMeshConfigs/hdtSMP64.xsd">

	<!--
		Cloaks of Skyrim cloak as a CROSSED 2-D tissue (pattern example). The whole CB grid (3 columns x 6 rows),
		its bone/constraint templates, and the warp+weft constraints all come from the shared
		"DaydreamingDay.cloak" pattern (patterns/DaydreamingDay.xml) via the single <pattern> use below. The
		pattern emits the cloth-simulation structure - the CB bones (which match this NIF's "CB 0c r" nodes)
		and how they interlink; it is reusable across any cloak NIF using that naming and a cols x rows grid.
		This file adds what is unique to THIS garment: the collision shapes, the body skeleton bones those
		shapes skin to, and the tuning overrides. Same real CB bones as the required SMP cloak NIF, so it binds
		in-game; needs FSMP with pattern support.

		The weft (horizontal) spring is the part you tune. It is a pattern parameter, so retune by
		overriding on the use, e.g. <pattern name="DaydreamingDay.cloak" weftStiffness="6"/> - no need to
		touch the library. See the override on the pattern use below.
	-->

	<per-triangle-shape name="VirtualGround">
		<margin>5</margin>
		<tag>ground</tag>
	</per-triangle-shape>

	<!--
		Body skeleton bones. These are NOT part of the cloak simulation: they carry no template, so
		they default to mass 0 (kinematic, animation-driven, never simulated), and they appear in no
		constraint. They are here because the body/feet collision meshes below (BaseShapeB -> body2,
		FeetB -> Feet) are skinned to them in the NIF. A per-triangle-shape's geometry follows the bones
		its vertices are weighted to, so each such bone must be declared as a <bone> or that part of the
		collision shape has nothing to move with. They give the cloak a body to drape over and collide
		against; remove one and the matching slice of body collision goes static.
	-->
	<bone name="NPC R ForearmA [RLar]"/>
	<bone name="NPC L ForearmA [LLar]"/>
	<bone name="CME R Forearm [RLar]"/>
	<bone name="CME L Forearm [LLar]"/>
	<bone name="SkirtBBone01"/>
	<bone name="SkirtBBone02"/>
	<bone name="SkirtBBone03"/>
	<bone name="NPC L RearCalf [LrClf]"/>
	<bone name="NPC R RearCalf [RrClf]"/>
	<bone name="NPC R Breast"/>
	<bone name="NPC R Breast01"/>
	<bone name="NPC L Breast"/>
	<bone name="NPC L Breast01"/>
	<bone name="NPC L Calf [LClf]"/>
	<bone name="NPC R Calf [RClf]"/>
	<bone name="NPC L Clavicle [LClv]"/>
	<bone name="NPC R Clavicle [RClv]"/>
	<bone name="NPC R Pauldron"/>
	<bone name="NPC L Pauldron"/>
	<bone name="NPC Head [Head]"/>
	<bone name="NPC Pelvis [Pelv]"/>
	<bone name="NPC Spine [Spn0]"/>
	<bone name="NPC Spine1 [Spn1]"/>
	<bone name="NPC Spine2 [Spn2]"/>

	<!--
		The whole crossed cloak, from the shared library: cols=3, rows=6, plus its bone templates
		(first, mass) and constraint templates (capeLoose, capeLimited, capeWeft). The default weft is
		a soft, non-Hookean spring; here we override two of its knobs to make this cloak's lateral
		cohesion a touch stiffer and roomier than the library default. Drop the attributes to fall back
		to the defaults (weftStiffness=4, weftLinearLimit=1, ...), or add more (weftDamping,
		weftAngularLimit, weftNonHookean) to retune further - all without editing patterns/DaydreamingDay.xml.
	-->
	<pattern name="DaydreamingDay.cloak" weftStiffness="6" weftLinearLimit="1.5"/>

	<!--
		Collision shapes stay HERE, in the consumer, not in the pattern - and deliberately so. A
		per-triangle-shape binds to a named mesh in THIS NIF (BaseShapeB, FeetB, Cloak, and VirtualGround
		above): the name must match a geometry the NIF actually contains, and its tag / no-collide-with-tag
		wire up this garment's collision groups. The pattern already names NIF nodes too (the CB cloth
		bones), but those follow a shared "CB 0c r" convention many cloaks reuse, so a grid pattern stays
		portable. Collision mesh names do not - they are unique to each garment's NIF, so a library meant
		for many cloaks cannot know them. That is why the cloth structure lives in the pattern while the
		shapes (and the body bones they skin to) live here in the consumer.
	-->
	<per-triangle-shape name="BaseShapeB">
		<margin>0</margin>
		<penetration>0</penetration>
		<tag>body2</tag>
		<no-collide-with-tag>body</no-collide-with-tag>
	</per-triangle-shape>

	<per-triangle-shape name="FeetB">
		<margin>0</margin>
		<penetration>0</penetration>
		<tag>Feet</tag>
		<no-collide-with-tag>body</no-collide-with-tag>
	</per-triangle-shape>

	<per-triangle-shape name="Cloak">
		<penetration>0</penetration>
		<tag>cloth</tag>
	</per-triangle-shape>

</system>
